baseURL = 'https://m1rm.github.io/hugo-techly/'
locale = 'en-us'
title = 'Hugo Theme Techly'

[module]
  [[module.imports]]
    path = 'github.com/m1rm/techly'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts/'
    weight = 20

[params]
  description = 'Showcase site for Techly, a simple Hugo theme for tech blogs.'
